version: '3.8'

services:
  frontend:
    image: subash729/frontend-v2:latest
    container_name: Frontend
    ports:
      - "5173:5173"
    networks:
      - bridge-frontend

networks:
  bridge-frontend:
    driver: bridge
