name: CI-build-and-push-images

on:
  workflow_run:
    workflows: ['CD-Deploy-container']
    types:
      - completed
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  image-build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Installing dependency
        working-directory: "devops/dependency-install"
        run: |
          chmod +x install.sh
          ./install.sh
      - name: Build image
        working-directory: "devops/frontend" 
        run: |
          docker build --no-cache -f FE-Dockerfile-multi-stage \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend-v2:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend-v2:$(git rev-parse --short HEAD) \
            ../../source-code/frontend/

  push_images:
    runs-on: self-hosted
    needs: [image-build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker frontend images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-v2:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-v2:$(git rev-parse --short HEAD)
      - name: Logout Docker
        run: |
          docker logout

  list_and_scan_images:
    runs-on: self-hosted
    needs: [push_images]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List Docker images
        run: |
          docker images
      - name: Scan images and upload artifact
        run: |
          SCAN_RESULT_FILE="./frontend_scan-$(git rev-parse HEAD)-$(date +'%Y-%m-%d_%H-%M').txt"
          trivy image --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/frontend-v2:$(git rev-parse --short HEAD) >> $SCAN_RESULT_FILE
      - name: Upload scan artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-scan-results
          path: ./$SCAN_RESULT_FILE
